### ISSUE TITLE
Tem algum exemplo para utilização?

### ISSUE THREAD

**Issue by adrianotrentim** [osamueloliveira/fiscalbr.net#1]
Amigo, você possui algum exemplo para a geração dos  arquivos? Estou perdidinho aqui!

**Comment by samuelrochaoliveira** [comment]
Fala @adrianotrentim, tudo em paz?

Tem um exemplo simples de geração da EFD Contribuições na página do SPEDBr antes da mesclagem para cá.

https://github.com/AOPack/SPEDBr.NET#exemplos

Se precisar de ajuda em algo mais é só avisar, qual é o seu cenário de geração? Industria, Comércio? Perfil A, B, C?

Abraços.
