### ISSUE TITLE
CodBarra do 0200 em branco.

### ISSUE THREAD

**Issue by rodrigofornasier** [osamueloliveira/FiscalBr.NET#13]
Boa noite Samuel,

Poderia me ajudar?
Estou com o problema de o CodBarra do 0200 sempre preenche em branco no arquivo texto, mesmo tendo conteúdo. Inclusive fiz o seguinte teste para ter certeza no meu código:

                            Bloco0.Registro0200 reg0200 = new Bloco0.Registro0200
                            {
                                ...
                                CodBarra = "1234567890123",
                                ...
                            };

Dei uma olhada no código da sua biblioteca, e achei o seguinte no método EscreverCampo:

         if (propertyLength > 0 && (propertyLength > fieldLength))
             return valorEscrever.Substring(0, fieldLength);

E como no Bloco0 está assim:

         [SpedCampos(4, "COD_BARRA", "C", 0, 0, false)]

Creio que seja esse o problema. Pode me ajudar?

Desde já fico grato.
Abraço!

**Comment by osamueloliveira** [comment]
Fala @rodrigofornasier, beleza?

Desculpa a demora.

Acabei de fazer a correção e encontra-se no commit [2ec9274](https://github.com/osamueloliveira/FiscalBr.NET/commit/2ec9274564b6e5320387efcfe55c98e6ea942df4).

Vida longa e próspera 🖖
