### ISSUE TITLE
Importar arquivo SPED

### ISSUE THREAD

**Issue by osamueloliveira** [osamueloliveira/fiscalbr.net#15]
Originalmente postada em https://github.com/AOPack/SPEDBr.NET/issues/53.

**Comment by marcosgerene** [comment]
@osamueloliveira 

Essa importação depende da indentificação dos filhos nos registros (ex: C100 -> C170, C190, ...)

Vou tentar me organizar aqui para fazer essa identificação no Sped Fiscal, fazendo, a gente tenta estudar a leitura.

**Comment by robertoandrade** [comment]
@marcosgerene isso foi implementado?

**Comment by marcosgerene** [comment]
@robertoandrade sim
