### ISSUE TITLE
Implementar Leitura de Arquivo Usando Reflection

### ISSUE THREAD

**Issue by osamueloliveira** [osamueloliveira/fiscalbr.net#16]
Originalmente postada em https://github.com/AOPack/SPEDBr.NET/issues/55.

**Comment by osamueloliveira** [comment]
Implementação iniciada no commit https://github.com/osamueloliveira/FiscalBr.NET/commit/6aebc0e965dc9c15becbdc1673cbee38aae1213c o/

**Comment by marcosgerene** [comment]
Sugestão:
https://github.com/osamueloliveira/fiscalbr.net/pull/25

**Comment by marcosgerene** [comment]
Feito para Sped Fiscal e Contribuições
