### ISSUE TITLE
Mapear SpedFiscalFile com Registros Pai e Filhos p/ Futura Leitura

### ISSUE THREAD

**Issue by osamueloliveira** [osamueloliveira/fiscalbr.net#17]
Originalmente postada em https://github.com/AOPack/SPEDBr.NET/issues/56.

**Comment by marcosgerene** [comment]
O mapeamento está sendo realizado, quase pronto.

Sobre a leitura, tenho uma sugestão:  https://github.com/osamueloliveira/fiscalbr.net/pull/25
