### ISSUE TITLE
[SpedFiscal] Mapear registros restantes do bloco D

### ISSUE THREAD

**Issue by osamueloliveira** [osamueloliveira/fiscalbr.net#18]
Originalmente postado em https://github.com/AOPack/SPEDBr.NET/issues/59.

Faltam os registros:
- [ ] D130;
- [ ] D140;
- [ ] D150;
- [ ] D160;
- [ ] D161;
- [ ] D162;
- [ ] D170;
- [ ] D180;
- [ ] D300;
- [ ] D301;
- [ ] D310;
- [ ] D350;
- [ ] D355;
- [ ] D360;
- [ ] D365;
- [ ] D370;
- [ ] D390;
- [ ] D400;
- [ ] D410;
- [ ] D411;
- [ ] D420;

**Comment by marcosgerene** [comment]
@osamueloliveira me chama no whatsapp!

Como está o desenvolvimento disso, tem alguém fazendo? Acredito que em alguns dias posso designar alguém para dar um gás nisso (mapeamentos)

**Comment by osamueloliveira** [comment]
Fala @marcosgerene tudo blz?

Rapaz, esse início de ano está bem complicado para mim, estou sem tempo.

Se você conseguir mapear ou alguém para mapear será uma mão na roda.

Vida longa e próspera 🖖

**Comment by marcosgerene** [comment]
@osamueloliveira conforme falamos no private, acredito que consigo designar alguém na próxima semana.
[]'s
