### ISSUE TITLE
como faço pra escrever o arquivo?

### ISSUE THREAD

**Issue by ThalisonSantos** [osamueloliveira/fiscalbr.net#31]
bom dia preenchi os blocos mas quando uso o método EscreverCampos ele retorna vazio, precisa fazer algo mais?

**Comment by ThalisonSantos** [comment]
Alguem?

**Comment by leandrossantos** [comment]
@ThalisonSantos dê uma olhada nesse código no link abaixo.

[https://pastebin.com/rNUDgja1](url)

**Comment by ThalisonSantos** [comment]
@leandrossantos esse link não abre nada

**Comment by leandrossantos** [comment]
> @leandrossantos esse link não abre nada

perdão, arrumei o link, pode clicar

**Comment by ThalisonSantos** [comment]
> > @leandrossantos esse link não abre nada
> 
> perdão, arrumei o link, pode clicar

@leandrossantos  então pelo que eu entendi tem escrever o arquivo linha a linha e não bloco a bloco é isso?

**Comment by ThalisonSantos** [comment]
consegui valeu
