### ISSUE TITLE
Importar arquivos SPED na nova base

### ISSUE THREAD

**Issue by GuilhermePX3** [osamueloliveira/fiscalbr.net#5]
Boa noite Samuel, primeiramente muito obrigado por compartilhar seu conhecimento!

Bom, eu estava dando uma olhada melhor na biblioteca presente no github do SPEDBr, eu percebi que lá havia uma função para puxar dados de um arquivo sped txt. Eu cheguei a baixar esse novo repositório também mas não encontrei algo relacionado à isso nessa nova base. Minha intenção é preencher os dados do arquivo sped em variáveis da biblioteca. Agradeço desde já!

**Comment by osamueloliveira** [comment]
Fala @GuilhermePX3 tudo em paz?

Então, essa funcionalidade começou a ser desenvolvida por mim e o @marcosgerene na outra lib, chamada SPEDBr.NET.

Tem vários campos tipados para receber as linhas e transformar nos objetos, está faltando um trabalhinho de develop aí para fazer o reflection funcionar.

Estou com uma demanda puxada nesse ano, por isso não consegui fazer ainda. Se puder e quiser contribuir será bem vindo.

Abraços.

**Comment by marcosgerene** [comment]
@GuilhermePX3  @osamueloliveira 

Eu comecei a fazer, mas o cliente que estava "patrocinando" desistiu, e eu também estou numa correria enorme, não consigo fazer a médio prazo, mas é uma baita funcionalidade para a ferramenta!

**Comment by GuilhermePX3** [comment]
Tudo certo!! Cara, eu achei muito interessante a ferramenta, facilita
bastante na hora de trabalhar com essas coisas. Tenho em mente fazer
algumas coisas também, mas a falta de tempo sempre complica. De qualquer
forma se sobrar um tempinho eu falo pra vcs o que eu tenho em mente..

Att.


Em qua, 16 de out de 2019 09:54, Marcos Gerene F. Spirito <
notifications@github.com> escreveu:

**Comment by osamueloliveira** [comment]
Fala @GuilhermePX3 @marcosgerene tudo em paz?

Eu comecei a implementar essa funcionalidade hoje, existe uma issue própria para o assunto https://github.com/osamueloliveira/FiscalBr.NET/issues/16.

Foram algumas horas gastas mas valeu a pena, até o momento só fiz testes na importação do Registro0000 da EFD Fiscal. Ainda preciso fazer alguns "polimentos" e incluir suporte para importação de campos de outros registros.

Atualmente a importação é feita linha a linha, nas próximas atualizações irei permitir a importação do TXT direto e leitura em massa.

Novidades serão postadas na issue https://github.com/osamueloliveira/FiscalBr.NET/issues/16.

Vida longa e próspera. 🖖

**Comment by marcosgerene** [comment]
Feito para Sped Fiscal e Contibuições
