### ISSUE TITLE
Migrar SPED.Br para o Fiscal.BR

### ISSUE THREAD

**Issue by rodrigofornasier** [osamueloliveira/FiscalBr.NET#7]
Olá!!!

Primeiro, meus parabéns pela bela iniciativa e trabalho, pretendo contribuir com o projeto tão logo eu tenha conhecimento do SPED, estou estudando a fundo o assunto.

Minha dúvida:

Eu fiz uma aplicação teste utilizando a biblioteca anterior (SpedBR), e gostaria de saber como faço para "migrar" na prática para esta biblioteca nova (FiscalBR). Na minha aplicação eu referenciei o seguinte:

SpedBr.Common.dll
SpedBr.Common.XML
SpedBr.Ecd.dll
SpedBr.Ecd.XML
SpedBr.Ecf.dll
SpedBr.Ecf.XML
SpedBr.EfdContribuicoes.dll
SpedBr.EfdContribuicoes.XML
SpedBr.Outros.Dimob.dll
SpedBr.Outros.Dimob.XML
SpedBr.SpedFiscal.dll
SpedBr.SpedFiscal.XML

No meu caso, eu vou gerar o SPED ICMS e SPED Contribuições. Como devo proceder?
Desde já peço desculpas pela pergunta "nível básico" e agradeço a ajuda.

Forte Abraço!!!

Rodrigo Fornasier

**Comment by adrianotrentim** [comment]
Fala Rodrigo, bom dia. Cara eu já iniciei no FiscalBr que é a ultima versão, não utilizei o SPEDBr... mas como referencia, no FiscalBr são apenas 3 referencias.... FiscalBr.Common, FiscalBr.SpedContribuicoes e FiscalBr.SpedFiscal.... para utilização é muito simples, um exemplo segue....  

foreach (var produto in produtos)
            {
                registros.Add(new Bloco0.Registro0200
                {
                    CodItem = produto.Codigo.ToString(),
                    DescrItem = produto.Descricao.RemoveAccents().ToUpper(),
                    CodBarra = "",
                    UnidInv = unidades.FirstOrDefault(t => t.Sigla == produto.UnidadeMedida.Sigla).Codigo.ToString(),
                    TipoItem = Convert.ToInt32(produto.GrupoProduto.IdTipoItemSPED).ToString().PadLeft(2, '0'),
                    CodNcm = produto.CodigoNCM?.ToString().PadLeft(8, '0'),
                    CodGen = produto.CodigoNCM?.ToString().PadLeft(8, '0').Substring(0, 2),
                    Cest = produto.CEST?.PadLeft(7, '0') == "0000000" ? "" : produto.CEST?.PadLeft(7, '0')
                });
            }

Onde regitros, é apenas um var registros = new List<dynamic>(); para gerar os arquivos em um StringBuilder depois.

Com relação a gerar os SPEDs, cara, na boa, troca uma idéia com o @osamueloliveira , ele além de desenvolvedor e pai do projeto, é consultor fiscal tbm, alias, eu entrei no projeto e fiz meu sped porque contratei ele para me ajudar na legislação, e acabei entrando como desenv aqui tbm....

**Comment by rodrigofornasier** [comment]
Obrigado Adriano.

Vou referenciar estas DLL's.
Eu já tinha implementado alguma coisa, acredito que pelo seu exemplo, não mudou nada.

Abraço!

**Comment by osamueloliveira** [comment]
Migração concluída, todos os arquivos SPED agora estão no FiscalBr.
